### ISSUE TITLE
how to get the resulting file name ?

### ISSUE THREAD

**Issue by parmentelat** [hoduche/git-graph#1]
Hey, I'm trying to build a git tutorial as a notebook; in the process I'd like to automatically show the inner objects as svg, and git-graph looks like an promising alternative

My workflow would then be to run something like `git graph -nc -f svg -c` but immediately after that I'd need to retrieve the name of the produced svg so I can embed it in my notebook

I could not see how to do that at first sight, what am I missing ?

thanks in any case !

**Comment by hoduche** [comment]
Hi, I am really sorry but my GitHub was not correctly set and was not notified of your issue.

In case it is still open, you could run:
`ls -A1t .gitGraph/ | grep .svg | head -1` immediately after generating the svg with `git graph` (this will output the name of the latest svg file in the .gitGraph folder where all graph representations are generated).
Would this solve your issue ?

Cheers.

**Comment by hoduche** [comment]
Hi. Good news: git-graph version 1.2 has just been released. It returns the produced image and its folder path.
